import math
print("**************************************")
print("Welcome to my first assignment !!")
print("*************************************")
a = int(input("Enter number a: "))
b = int(input("Enter number b: "))
print("a**b =",a**b)
print("log(a) is",math.log2(a))
print("My student ID is 75852")
print("**************************************")
